---
version: 2.1

parameters:
  workspace-dir:
    type: string
    default: "/home/circleci"

commands:
  setup:
    description: "install go, checkout and restore cache"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install ocl-icd-opencl-dev
      - run: git submodule sync
      - run: git submodule update --init
      - run: cd extra/filecoin-ffi && make

executors:
  golang:
    docker:
      - image: circleci/golang:1.14.6
    resource_class: 2xlarge

workflows:
  version: 2
  main:
    jobs:
      - soup-build-linux

jobs:
  soup-build-linux:
    executor: golang
    steps:
      - setup
      - run:
          name: "build lotus-soup"
          command: pushd lotus-soup && go build -tags=testground .
