[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "lotus-baseline"
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"

[global.build_config]
  enable_go_build_cache = true

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build]
    selectors = ["testground"]
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
      clients = "1"
      miners = "1"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build]
    selectors = ["testground"]
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      clients = "1"
      miners = "1"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"


[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build]
    selectors = ["testground"]
  [groups.run]
    [groups.run.test_params]
      role = "client"
      clients = "1"
      miners = "1"
      balance = "2000000000"
      sectors = "10"
      random_beacon_type = "mock"

