[metadata]
  name = "lotus-soup"
  author = "raulk"

[global]
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "docker:go"
  runner = "local:docker"

[global.build_config]
  enable_go_build_cache = true

[global.run_config]
  exposed_ports = ["6060", "1234", "2345"]

[global.build]
  selectors = ["testground"]

[global.run.test_params]
  clients = "2"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "2000000000"
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]
  id = "miners"
  instances = { count = 2 }
  [groups.run.test_params]
    role = "miner"

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"
