name = "lotus-soup"
extra_sources = { "exec:go" = ["../extra/filecoin-ffi"] }

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
build_base_image = "iptestground/oni-buildbase:v1"
runtime_image = "iptestground/oni-runtime:v1"
enable_go_build_cache = true
skip_runtime_image = false

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "lotus-baseline"
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients = { type = "int", default = 1 }
  miners = { type = "int", default = 1 }
  balance = { type = "int", default = 1 }
  sectors = { type = "int", default = 1 }
  role = { type = "string" }
