name = "lotus-soup"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
runtime_image = "iptestground/oni-runtime:596ed33"
build_base_image = "iptestground/oni-buildbase:596ed33"
enable_go_build_cache = true
skip_runtime_image = false

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "lotus-baseline"
instances = { min = 1, max = 100, default = 5 }
