name = "lotus-testground"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
skip_runtime_image = false

[builders."docker:go".dockerfile_extensions]
pre_mod_download = """
RUN apt-get update && apt-get install -y ca-certificates llvm clang mesa-opencl-icd ocl-icd-opencl-dev jq gcc git bzr pkg-config
ARG LOTUS_VERSION=c6a8fe16
RUN git clone https://github.com/filecoin-project/lotus.git ${PLAN_DIR}/../lotus && cd ${PLAN_DIR}/../lotus && git checkout ${LOTUS_VERSION} && git submodule update --init
RUN cd ${PLAN_DIR}/../lotus/extern/filecoin-ffi \
    && make \
    && mkdir /tmp/filecoin-ffi \
    && cp -R ${PLAN_DIR}/../lotus/extern/filecoin-ffi /tmp
"""

post_runtime_copy = """
COPY --from=builder /usr/lib/x86_64-linux-gnu/* /lib/x86_64-linux-gnu/* /usr/lib/
COPY --from=builder /lotus/build/bootstrap/* /lotus/build/bootstrap/
COPY --from=builder /lotus/build/proof-params/* /lotus/build/proof-params/
"""

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "lotus-network"
instances = { min = 3, max = 3, default = 3 }

[testcases.params]
   miner-count = { type = "int", default = 1 }
